name: WP MyGitHub Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  runPHPCSInspection:

    name: Run PHPCS inspection

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2



      - name: Setup PHP

        uses: shivammathur/setup-php@v2

        with:

          php-version: '7.0'

          coverage: none

          tools: cs2pr, composer:v1


      - name: Install dependencies

        run: composer install --prefer-dist --no-suggest --no-progress


      - name: Get composer cache directory

        id: composercache

        run: echo "::set-output name=dir::$(composer config cache-files-dir)"



      - name: Cache dependencies

        uses: actions/cache@v2

        with:

          path: ${{ steps.composercache.outputs.dir }}

          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

          restore-keys: ${{ runner.os }}-composer-


      - id: changes

        run: |

          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"

          FILES=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -s -X GET -G $URL | jq -r '.[] | .filename' | xargs)

          echo "::set-output name=files::$FILES"


      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: phpcs.xml

      - name: Detect coding standard violations

        run: vendor/bin/phpcs ${{ steps.changes.outputs.files }} -q --report=checkstyle | cs2pr --graceful-warnings
